DECLARE
BEGIN
  
  FOR LINHA IN ( SELECT * FROM TOTVS12PRD.SF1010_MANFRINY_121118 ) LOOP
    UPDATE 
      TOTVS12PRD.SF1010 X
    SET 
      X.F1_DTLANC = LINHA.F1_DTLANC
    WHERE
      X.R_E_C_N_O_ = LINHA.R_E_C_N_O_;            
  END LOOP;

END;
