DEFINE FILIAL='0301';
DEFINE nf='000002239';
DEFINE LOTE_ERRADO='S32-74I77/002';
DEFINE LOTE_CERTO='S32-74I77/005';

SELECT * FROM SD1010 WHERE D1_FILIAL='&FILIAL' AND D1_DOC='&nf' AND D1_LOTECTL='&LOTE_ERRADO';
SELECT * FROM NP9010 WHERE NP9_FILIAL='&FILIAL' AND NP9_DOC='&nf' AND NP9_LOTE='&LOTE_ERRADO';
SELECT * FROM SB8010 WHERE B8_FILIAL='&FILIAL' AND B8_DOC='&nf' AND B8_LOTECTL='&LOTE_ERRADO';

UPDATE SD1010 SET D1_LOTECTL='&LOTE_CERTO' WHERE D1_FILIAL='&FILIAL' AND D1_DOC='&nf' AND D1_LOTECTL='&LOTE_ERRADO' AND D_E_L_E_T_=' ';
UPDATE NP9010 SET NP9_LOTE='&LOTE_CERTO' WHERE NP9_FILIAL='&FILIAL' AND NP9_DOC='&nf' AND NP9_LOTE='&LOTE_ERRADO' AND D_E_L_E_T_=' ';

--Foi orientada a fazer a desmontagem do lote errado para o lote certo para ajustar o saldos em estoque.