--busca veículos sem movimento no gfe
select da3_cod from da3010 where D_E_L_E_T_=' ' and  da3_placa not in(
select gx6_cdveic from (
select GX4_FILIAL, GX4_NRMOV, GX3_CDOPER, GX4_CDPTCT, GX6_CDVEIC, GX6_DTENTR, GX6_HRENTR, GX6_DTSAI, GX6_HRSAI, 
GX4_SIT, GX3_SIT,
CASE   
      WHEN GX4_SIT = 1 THEN 'NAO AVALIADO'
   WHEN GX4_SIT = 2 THEN 'APROVADO'
   WHEN GX4_SIT = 3 THEN 'REPROVADO'
   ELSE 'NAO INFORMADO'
END AS SIT_GX4, 
CASE   
      WHEN GX3_SIT = 1 THEN 'ABERTO'
   WHEN GX3_SIT = 2 THEN 'MOVIMENTADO'
   WHEN GX3_SIT = 3 THEN 'EM FILA'
   WHEN GX3_SIT = 4 THEN 'ENDERECADO'
   WHEN GX3_SIT = 5 THEN 'CANCELADO'
   WHEN GX3_SIT = 6 THEN 'CONCLUIDO'
   ELSE 'NAO INFORMADO'
END AS SIT_GX3
from GX4010 GX4
Inner join GX3010 GX3 ON GX3.D_E_L_E_T_ = ' ' AND GX3_NRMOV = GX4_NRMOV AND GX3_FILIAl = GX4_FILIAL
Inner join GX6010 GX6 ON GX6.D_E_L_E_T_ = ' ' AND GX6_NRMOV = GX4_NRMOV AND GX6_FILIAl = GX4_FILIAL
WHERE GX4.D_E_L_E_T_ = ' ' AND GX4_FILIAL = '0301'));

--busca veículos sem movimento no gfe
select da3_cod from da3010 where D_E_L_E_T_=' ' and  da3_placa not in(
select gx6_cdveic from (
select GX4_FILIAL, GX4_NRMOV, GX3_CDOPER, GX4_CDPTCT, GX6_CDVEIC, GX6_DTENTR, GX6_HRENTR, GX6_DTSAI, GX6_HRSAI, 
GX4_SIT, GX3_SIT,GX8.GX8_CDMTR
CASE   
      WHEN GX4_SIT = 1 THEN 'NAO AVALIADO'
   WHEN GX4_SIT = 2 THEN 'APROVADO'
   WHEN GX4_SIT = 3 THEN 'REPROVADO'
   ELSE 'NAO INFORMADO'
END AS SIT_GX4, 
CASE   
      WHEN GX3_SIT = 1 THEN 'ABERTO'
   WHEN GX3_SIT = 2 THEN 'MOVIMENTADO'
   WHEN GX3_SIT = 3 THEN 'EM FILA'
   WHEN GX3_SIT = 4 THEN 'ENDERECADO'
   WHEN GX3_SIT = 5 THEN 'CANCELADO'
   WHEN GX3_SIT = 6 THEN 'CONCLUIDO'
   ELSE 'NAO INFORMADO'
END AS SIT_GX3
from GX4010 GX4
Inner join GX3010 GX3 ON GX3.D_E_L_E_T_ = ' ' AND GX3_NRMOV = GX4_NRMOV AND GX3_FILIAl = GX4_FILIAL
Inner join GX6010 GX6 ON GX6.D_E_L_E_T_ = ' ' AND GX6_NRMOV = GX4_NRMOV AND GX6_FILIAl = GX4_FILIAL
Inner join GX8010 GX8 ON GX8.D_E_L_E_T_ = ' ' AND GX8_NRMOV = GX4_NRMOV AND GX8_FILIAl = GX4_FILIAL
WHERE GX4.D_E_L_E_T_ = ' ' AND GX4_FILIAL = '0301'));
