         
SET SERVEROUTPUT ON
DECLARE CURSOR CUR1 IS SELECT * FROM TABELA;

BEGIN
  DBMS_OUTPUT.PUT_LINE('TABELA');
  FOR R1 IN CUR1 LOOP
	  UPDATE TABELA SET CAMPO=R1.CAMPO WHERE TABELA.CHAVE = R1.CHAVE;
  DBMS_OUTPUT.PUT_LINE('                '||TO_Char(SQL%ROWCOUNT)||' linha(s) atualizada(s).'); --saida no console
  END LOOP;
END;