
select * from FVGATEC.GA_SALE_ORDER_ITEM where ORDER_ID=48381 and ACTIVE=1;

update FVGATEC.GA_SALE_ORDER_ITEM set ACTIVE=0,SYS_LAST_CHANGE_DATE=SYSDATE,INACTIVE_DATE=SYSDATE,SYS_USER_NAME_LAST_CHANGE='Ana Paula Guimaraes' where ORDER_ID=48381 and ID=86789;