--== SELECT DA COTABILIZACAO DAS EMPRESAS TUDO
SELECT
FILIAL,
MES,
ANO,
DATALAN,
NUM,
HIST,
DESCHIS,
TO_CHAR(COMP) AS COMP,
CONTA,
DESCONTA,
DC,
SUM(VALOR_DEBITO) AS VALOR_DEBITO,
SUM(VALOR_CREDITO) AS VALOR_CREDITO,
CASE WHEN CTT IN ('1','3','4','9') THEN
(SUM(VALOR_DEBITO) - SUM(VALOR_CREDITO))
WHEN CTT IN ('2','5','7') THEN
(SUM(VALOR_CREDITO) - SUM(VALOR_DEBITO)) END AS SALDO,
CTT,
LP,
TPSALDO
FROM(
SELECT 
LAN.CODI_EMP AS FILIAL,
TO_CHAR (CAB.DATA_CLC,'MM') AS MES,
TO_CHAR (CAB.DATA_CLC,'YYYY') AS ANO,
CAB.DATA_CLC AS DATALAN,
LAN.SEQU_LCT AS NUM,
LAN.HIST_HIS AS HIST,
HIS.DESC_HIS AS DESCHIS,
LAN.COMP_LCT AS COMP,
LAN.CODI_CPC AS CONTA,
CTT.DESC_CPC AS DESCONTA,
LAN.TIPO_LCT AS DC,
(CASE WHEN LAN.TIPO_LCT = 'D' THEN LAN.VLOR_LCT  ELSE 0 END)   AS VALOR_DEBITO,
(CASE WHEN LAN.TIPO_LCT = 'C' THEN LAN.VLOR_LCT  ELSE 0 END)   AS VALOR_CREDITO,
CTT.GRUP_CPC AS CTT,
CAB.ORIG_CLC AS LP,
CAB.TIPO_CLC AS TPSALDO
FROM SYSDBA.LANCONTAB LAN
LEFT JOIN SYSDBA.CABLANCTB CAB ON CAB.SEQU_CLC=LAN.SEQU_CLC
LEFT JOIN SYSDBA.CONTASPL CTT ON CTT.CODI_CPC=LAN.CODI_CPC AND CTT.CODI_PLC='1'
LEFT JOIN SYSDBA.HISTORICO HIS ON HIS.HIST_HIS=LAN.HIST_HIS


WHERE 
LAN.CODI_EMP IN (1,2,3,4,5,6,7,8)
AND CAB.TIPO_CLC IN ('F')
AND CAB.DATA_CLC BETWEEN '13/11/20' AND '13/11/20'
AND (CAB.ORIG_CLC<>'ZR') 
AND (LAN.CODI_CPC<>'51110101001')
AND (LAN.CODI_CPC BETWEEN '91110101016' AND '91110101099')


)VW 
GROUP BY FILIAL, MES, ANO, DATALAN, NUM, HIST, DESCHIS, TO_CHAR(COMP), CONTA, DESCONTA, DC, CTT, LP, TPSALDO
ORDER BY FILIAL, DATALAN, CONTA





/* artigo ensiando a converter o clob do erro para varchar

http://www.dba-oracle.com/t_convert_blob_varchar_datatype.htm