SELECT DISTINCT C9_OK OK, C9_FILIAL FILPED, C9_CARGA CODCARGA, C9_SEQCAR SEQCAR, C9_PEDIDO PEDIDO, C9_ITEM ITEM, C9_SEQUEN SEQUENCIA,
	C9_PRODUTO PRODUTO, C6_UM UM, C9_QTDLIB QTDE, C6_LOCAL LOCAL, C6_CULTRA CULTRA, 
	C6_CTVAR CULTVAR, C6_CATEG CATEG , C6_PENE PENE, B1_DESC DSPRODUTO, 
	SC9.D_E_L_E_T_, SC9.R_E_C_N_O_, SC9.R_E_C_D_E_L_ , ( C9_QTDLIB -  ( SELECT NVL( (SELECT SUM(NJ6S.NJ6_QTDE) NJ6_QTDS 
																		FROM NJ6010 NJ6S 
																		WHERE NJ6S.NJ6_FILIAL = C9_FILIAL 
																		AND NJ6S.NJ6_NUMPV = C9_PEDIDO 
																		AND NJ6S.NJ6_ITEM = C9_ITEM  
																		AND NJ6S.NJ6_SEQUEN = C9_SEQUEN 
																		AND NJ6S.NJ6_PRODUT = C9_PRODUTO 
																		AND NJ6S.D_E_L_E_T_ <> '*' ) , 0 ) FROM DUAL ) ) SALDO 
	FROM SC9010 SC9
    INNER JOIN SC6010 SC6 ON C9_FILIAL = C6_FILIAL AND 
    C9_PEDIDO = C6_NUM AND C9_ITEM = C6_ITEM AND C9_PRODUTO = C6_PRODUTO 

	LEFT JOIN NJ5010 NJ5 ON C9_FILIAL = NJ5_FILIAL AND 
	C9_PEDIDO = NJ5_NUMPV AND C9_ITEM = NJ5_ITEM AND 
	C9_SEQUEN = NJ5_SEQUEN AND C9_PRODUTO = NJ5_PRODUT 

	LEFT JOIN NJ6010 NJ6 ON C9_FILIAL = NJ6_FILIAL AND 
	C9_PEDIDO = NJ6_NUMPV AND C9_ITEM = NJ6_ITEM AND 
	C9_SEQUEN = NJ6_SEQUEN AND C9_PRODUTO = NJ6_PRODUT 

	LEFT JOIN SB1010 SB1 ON B1_FILIAL = '0301' AND C9_PRODUTO = B1_COD 								

	WHERE 1=1 
	AND SC9.C9_BLCRED = ' ' 
	AND NJ5.NJ5_STATUS IN ( '2', '3' ) 
	AND SC9.C9_QTDLIB > ( SELECT NVL( (SELECT SUM(NJ6S.NJ6_QTDE) NJ6_QTDS 
						FROM NJ6010 NJ6S 
						WHERE NJ6S.NJ6_FILIAL = C9_FILIAL 
						AND NJ6S.NJ6_NUMPV = C9_PEDIDO 
						AND NJ6S.NJ6_ITEM = C9_ITEM  
						AND NJ6S.NJ6_SEQUEN = C9_SEQUEN 
						AND NJ6S.NJ6_PRODUT = C9_PRODUTO 
						AND NJ6S.D_E_L_E_T_ <> '*' ) , 0 ) FROM DUAL ) 
	
	AND SC9.D_E_L_E_T_ <> '*' 
	AND ( ( SC6.D_E_L_E_T_ = ' '   AND SC9.D_E_L_E_T_ = ' '    AND NJ5.D_E_L_E_T_ = ' ' )
	OR ( SC6.D_E_L_E_T_ = ' '   AND SC9.D_E_L_E_T_ = ' '    AND NJ5.D_E_L_E_T_ IS NULL ) 
	OR ( SC6.D_E_L_E_T_ IS NULL AND SC9.D_E_L_E_T_ IS NULL  AND NJ5.D_E_L_E_T_ IS NULL ) 
	OR ( SC6.D_E_L_E_T_ = ' '   AND SC9.D_E_L_E_T_ = ' '    AND NJ5.D_E_L_E_T_ = '*' ) 
	OR ( SC6.D_E_L_E_T_ = ' '   AND SC9.D_E_L_E_T_ = '*'    AND NJ5.D_E_L_E_T_ = '*' ) 
	OR ( SC6.D_E_L_E_T_ = ' '   AND SC9.D_E_L_E_T_ = '*'    AND NJ5.D_E_L_E_T_ IS NULL )); 