
SELECT
      SPED.NFE_ID,
      UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(XML_ERP,500,1)) AS XML_ERP,
      UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(XML_SIG,500,1)) AS XML_SIG,
      UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(XML_SIGCAN,500,1)) AS XML_SIGCAN
FROM
      SPED.SPED050 SPED;